version: 2

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./demo:/demo
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.1-fpm
    volumes:
      - ./demo:/demo
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
