<?php


 function autoload_a8ce2539a42f22a9b0f2f78e83bb9d9c($class)
{
    $classes = array(
        'ProviderExchangeNetwork\Soap\Objects\DSIRating' => __DIR__ .'/DSIRating.php',
        'ProviderExchangeNetwork\Soap\Objects\RegistrationAction' => __DIR__ .'/RegistrationAction.php',
        'ProviderExchangeNetwork\Soap\Objects\TimeZone' => __DIR__ .'/TimeZone.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfRatingMethod' => __DIR__ .'/ArrayOfRatingMethod.php',
        'ProviderExchangeNetwork\Soap\Objects\RatingMethod' => __DIR__ .'/RatingMethod.php',
        'ProviderExchangeNetwork\Soap\Objects\CarStatus' => __DIR__ .'/CarStatus.php',
        'ProviderExchangeNetwork\Soap\Objects\DealType' => __DIR__ .'/DealType.php',
        'ProviderExchangeNetwork\Soap\Objects\Language' => __DIR__ .'/Language.php',
        'ProviderExchangeNetwork\Soap\Objects\UserRole' => __DIR__ .'/UserRole.php',
        'ProviderExchangeNetwork\Soap\Objects\DeductibleType' => __DIR__ .'/DeductibleType.php',
        'ProviderExchangeNetwork\Soap\Objects\AnnouncementType' => __DIR__ .'/AnnouncementType.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfint' => __DIR__ .'/ArrayOfint.php',
        'ProviderExchangeNetwork\Soap\Objects\DSISetDealerRequest' => __DIR__ .'/DSISetDealerRequest.php',
        'ProviderExchangeNetwork\Soap\Objects\DSISetDealerResponse' => __DIR__ .'/DSISetDealerResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\Error' => __DIR__ .'/Error.php',
        'ProviderExchangeNetwork\Soap\Objects\DSISetDealerProductRequest' => __DIR__ .'/DSISetDealerProductRequest.php',
        'ProviderExchangeNetwork\Soap\Objects\DSISetDealerProductResponse' => __DIR__ .'/DSISetDealerProductResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetProvidersResponse' => __DIR__ .'/DSIGetProvidersResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfProvider' => __DIR__ .'/ArrayOfProvider.php',
        'ProviderExchangeNetwork\Soap\Objects\Provider' => __DIR__ .'/Provider.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetProductsResponse' => __DIR__ .'/DSIGetProductsResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfProduct' => __DIR__ .'/ArrayOfProduct.php',
        'ProviderExchangeNetwork\Soap\Objects\Product' => __DIR__ .'/Product.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetLendersRequest' => __DIR__ .'/DSIGetLendersRequest.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetLendersResponse' => __DIR__ .'/DSIGetLendersResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfLender' => __DIR__ .'/ArrayOfLender.php',
        'ProviderExchangeNetwork\Soap\Objects\Lender' => __DIR__ .'/Lender.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetRateBookCodesRequest' => __DIR__ .'/DSIGetRateBookCodesRequest.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetRateBookCodesResponse' => __DIR__ .'/DSIGetRateBookCodesResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfRateBookCode' => __DIR__ .'/ArrayOfRateBookCode.php',
        'ProviderExchangeNetwork\Soap\Objects\RateBookCode' => __DIR__ .'/RateBookCode.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetModelsResponse' => __DIR__ .'/DSIGetModelsResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfModel' => __DIR__ .'/ArrayOfModel.php',
        'ProviderExchangeNetwork\Soap\Objects\Model' => __DIR__ .'/Model.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetSurchargesResponse' => __DIR__ .'/DSIGetSurchargesResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfSurcharge' => __DIR__ .'/ArrayOfSurcharge.php',
        'ProviderExchangeNetwork\Soap\Objects\Surcharge' => __DIR__ .'/Surcharge.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetRatesRequest' => __DIR__ .'/DSIGetRatesRequest.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIDealInfo' => __DIR__ .'/DSIDealInfo.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfDSIProductInfo' => __DIR__ .'/ArrayOfDSIProductInfo.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIProductInfo' => __DIR__ .'/DSIProductInfo.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfDSISurcharge' => __DIR__ .'/ArrayOfDSISurcharge.php',
        'ProviderExchangeNetwork\Soap\Objects\DSISurcharge' => __DIR__ .'/DSISurcharge.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetRatesResponse' => __DIR__ .'/DSIGetRatesResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfRate' => __DIR__ .'/ArrayOfRate.php',
        'ProviderExchangeNetwork\Soap\Objects\Rate' => __DIR__ .'/Rate.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfCoverage' => __DIR__ .'/ArrayOfCoverage.php',
        'ProviderExchangeNetwork\Soap\Objects\Coverage' => __DIR__ .'/Coverage.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfDeductible' => __DIR__ .'/ArrayOfDeductible.php',
        'ProviderExchangeNetwork\Soap\Objects\Deductible' => __DIR__ .'/Deductible.php',
        'ProviderExchangeNetwork\Soap\Objects\Form' => __DIR__ .'/Form.php',
        'ProviderExchangeNetwork\Soap\Objects\Market' => __DIR__ .'/Market.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfRedemption' => __DIR__ .'/ArrayOfRedemption.php',
        'ProviderExchangeNetwork\Soap\Objects\Redemption' => __DIR__ .'/Redemption.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfSurcharged' => __DIR__ .'/ArrayOfSurcharged.php',
        'ProviderExchangeNetwork\Soap\Objects\Surcharged' => __DIR__ .'/Surcharged.php',
        'ProviderExchangeNetwork\Soap\Objects\Vehicle' => __DIR__ .'/Vehicle.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetQuoteRequest' => __DIR__ .'/DSIGetQuoteRequest.php',
        'ProviderExchangeNetwork\Soap\Objects\DSICoverageInfo' => __DIR__ .'/DSICoverageInfo.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetQuoteResponse' => __DIR__ .'/DSIGetQuoteResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\Quote' => __DIR__ .'/Quote.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetBatchRatesResponse' => __DIR__ .'/DSIGetBatchRatesResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfLevel' => __DIR__ .'/ArrayOfLevel.php',
        'ProviderExchangeNetwork\Soap\Objects\Level' => __DIR__ .'/Level.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetDealersResponse' => __DIR__ .'/DSIGetDealersResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfDealer' => __DIR__ .'/ArrayOfDealer.php',
        'ProviderExchangeNetwork\Soap\Objects\Dealer' => __DIR__ .'/Dealer.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetDealerProductsResponse' => __DIR__ .'/DSIGetDealerProductsResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfDealerProduct' => __DIR__ .'/ArrayOfDealerProduct.php',
        'ProviderExchangeNetwork\Soap\Objects\DealerProduct' => __DIR__ .'/DealerProduct.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetAnnouncementRequest' => __DIR__ .'/DSIGetAnnouncementRequest.php',
        'ProviderExchangeNetwork\Soap\Objects\DSIGetAnnouncementResponse' => __DIR__ .'/DSIGetAnnouncementResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\ArrayOfAnnouncement' => __DIR__ .'/ArrayOfAnnouncement.php',
        'ProviderExchangeNetwork\Soap\Objects\Announcement' => __DIR__ .'/Announcement.php',
        'ProviderExchangeNetwork\Soap\Objects\SetDealer' => __DIR__ .'/SetDealer.php',
        'ProviderExchangeNetwork\Soap\Objects\SetDealerResponse' => __DIR__ .'/SetDealerResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\SetDealerProduct' => __DIR__ .'/SetDealerProduct.php',
        'ProviderExchangeNetwork\Soap\Objects\SetDealerProductResponse' => __DIR__ .'/SetDealerProductResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetProviders' => __DIR__ .'/GetProviders.php',
        'ProviderExchangeNetwork\Soap\Objects\GetProvidersResponse' => __DIR__ .'/GetProvidersResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetProducts' => __DIR__ .'/GetProducts.php',
        'ProviderExchangeNetwork\Soap\Objects\GetProductsResponse' => __DIR__ .'/GetProductsResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetLenders' => __DIR__ .'/GetLenders.php',
        'ProviderExchangeNetwork\Soap\Objects\GetLendersResponse' => __DIR__ .'/GetLendersResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetRateBookCodes' => __DIR__ .'/GetRateBookCodes.php',
        'ProviderExchangeNetwork\Soap\Objects\GetRateBookCodesResponse' => __DIR__ .'/GetRateBookCodesResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetModels' => __DIR__ .'/GetModels.php',
        'ProviderExchangeNetwork\Soap\Objects\GetModelsResponse' => __DIR__ .'/GetModelsResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetSurcharges' => __DIR__ .'/GetSurcharges.php',
        'ProviderExchangeNetwork\Soap\Objects\GetSurchargesResponse' => __DIR__ .'/GetSurchargesResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetRates' => __DIR__ .'/GetRates.php',
        'ProviderExchangeNetwork\Soap\Objects\GetRatesResponse' => __DIR__ .'/GetRatesResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetQuote' => __DIR__ .'/GetQuote.php',
        'ProviderExchangeNetwork\Soap\Objects\GetQuoteResponse' => __DIR__ .'/GetQuoteResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetBatchRates' => __DIR__ .'/GetBatchRates.php',
        'ProviderExchangeNetwork\Soap\Objects\GetBatchRatesResponse' => __DIR__ .'/GetBatchRatesResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetDealers' => __DIR__ .'/GetDealers.php',
        'ProviderExchangeNetwork\Soap\Objects\GetDealersResponse' => __DIR__ .'/GetDealersResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetDealerProducts' => __DIR__ .'/GetDealerProducts.php',
        'ProviderExchangeNetwork\Soap\Objects\GetDealerProductsResponse' => __DIR__ .'/GetDealerProductsResponse.php',
        'ProviderExchangeNetwork\Soap\Objects\GetAnnouncements' => __DIR__ .'/GetAnnouncements.php',
        'ProviderExchangeNetwork\Soap\Objects\GetAnnouncementsResponse' => __DIR__ .'/GetAnnouncementsResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_a8ce2539a42f22a9b0f2f78e83bb9d9c');

// Do nothing. The rest is just leftovers from the code generation.
{
}
